# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = lib.mkForce
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/iso" = lib.mkForce
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/nix/.ro-store" = lib.mkForce
    { device = "/iso/nix-store.squashfs";
      fsType = "squashfs";
      options = [ "loop" ];
    };

  fileSystems."/nix/.rw-store" = lib.mkForce
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/nix/store" = lib.mkForce
    { device = "overlay";
      fsType = "overlay";
    };

  fileSystems."/mnt" = lib.mkForce
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."cryptroot".device = lib.mkForce "/dev/disk/by-uuid/0d7b0fa7-4f14-4f1f-bef2-6b7c95de01ff";

  fileSystems."/mnt/.snapshots" = lib.mkForce
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/mnt/boot" = lib.mkForce
    { device = "/dev/disk/by-uuid/3127-89D4";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/home" = lib.mkForce
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/mnt/home/angelus/data" = lib.mkForce
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "subvol=@data" ];
    };

  fileSystems."/mnt/nix" = lib.mkForce
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/mnt/var" = lib.mkForce
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
