# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "rpool/nixos/empty";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/929C-5468";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/cache" =
    {
      device = "cache/data";
      fsType = "zfs";
    };

  fileSystems."/data1" =
    {
      device = "/dev/disk/by-uuid/0fd96c56-7ed5-4489-9404-96d460d1cae8";
      fsType = "xfs";
    };

  fileSystems."/data2" =
    {
      device = "/dev/disk/by-uuid/a2790f3f-58de-44b8-9fe0-f765363d80f5";
      fsType = "xfs";
    };

  fileSystems."/data3" =
    {
      device = "/dev/disk/by-uuid/bfd9fc8f-2a31-4e9b-8d22-e09354b551c9";
      fsType = "xfs";
    };

  fileSystems."/data4" =
    {
      device = "/dev/disk/by-uuid/434c3e5a-ce36-4489-af37-c6c6c1f9fb1e";
      fsType = "xfs";
    };

  fileSystems."/home" =
    {
      device = "rpool/nixos/home";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    {
      device = "rpool/nixos/nix";
      fsType = "zfs";
    };

  fileSystems."/parity1" =
    {
      device = "/dev/disk/by-uuid/222910c8-980b-4446-b4c3-ef09d0836785";
      fsType = "xfs";
    };

  fileSystems."/persist" =
    {
      device = "rpool/nixos/persist";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
