# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/nixos/empty";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7854-DEDD";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "rpool/nixos/home";
      fsType = "zfs";
    };

  fileSystems."/mnt/data1" =
    { device = "/dev/disk/by-uuid/fb9c328b-f050-4f1f-a6c8-fd97e8bc3d75";
      fsType = "xfs";
    };

  fileSystems."/mnt/data2" =
    { device = "/dev/disk/by-uuid/9d5331f3-30d1-4ea9-bda6-e1a764da8a9d";
      fsType = "xfs";
    };

  fileSystems."/mnt/data3" =
    { device = "/dev/disk/by-uuid/8cd3dad2-e1f5-4773-bbb2-e129a07725df";
      fsType = "xfs";
    };

  fileSystems."/mnt/data4" =
    { device = "/dev/disk/by-uuid/68d68b7f-f712-41c8-a299-21079239c259";
      fsType = "xfs";
    };

  fileSystems."/mnt/parity1" =
    { device = "/dev/disk/by-uuid/bc75c502-81c5-468f-981f-0a4091ceb416";
      fsType = "xfs";
    };

  fileSystems."/nix" =
    { device = "rpool/nixos/nix";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "rpool/nixos/persist";
      fsType = "zfs";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
